# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('IPHONE', 'iPhone'), ('IPAD', 'iPad'), ('IMAC', 'iMac'), ('MACBOOK', 'MacBook'), ('OTHER', 'Other')], default='IPHONE', max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bom',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_list', to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_list', to='shop.Supplier'),
        ),
        migrations.AlterField(
            model_name='receiving_detail',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiv_bom_list', to='shop.Bom'),
        ),
        migrations.AlterField(
            model_name='receiving_detail',
            name='po_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiv_detail_list', to='shop.Receiving'),
        ),
    ]
