# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20161001_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
