# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20161001_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('IN', 'Inventory'), ('SOLD', 'Sold out'), ('CLIAM', 'Cliam'), ('SCRAP', 'Scrapped'), ('OTHER', 'Other')], default='IN', max_length=50),
        ),
    ]
