# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_inventory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close')], default='OPEN', max_length=50),
        ),
    ]
