# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_receiving_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='bom_part',
            new_name='bom',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='receiving',
            new_name='receiving_detail',
        ),
        migrations.RenameField(
            model_name='receiving_detail',
            old_name='part_number',
            new_name='bom',
        ),
        migrations.RenameField(
            model_name='receiving_detail',
            old_name='po_number',
            new_name='receiving',
        ),
    ]
